### ISSUE TITLE
Compilation errors on julia 1.0

### ISSUE THREAD

**Issue by natschil** [JuliaGeometry/VoronoiDelaunay.jl#40]
It seems like this package does not work on julia 1.0, is anyone looking into how this could be fixed? 

I currently get errors like this one: 

```
julia> using VoronoiDelaunay
[ Info: Precompiling VoronoiDelaunay [72f80fcb-8c52-57d9-aff0-40c1a3526986]
ERROR: LoadError: syntax: extra token "DelaunayTriangle" after end of expression
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:319 [inlined]
 [6] eval(::Expr) at ./client.jl:389
 [7] top-level scope at ./none:3
in expression starting at /home/nathanael/.julia/packages/VoronoiDelaunay/Tqbb6/src/VoronoiDelaunay.jl:30
ERROR: Failed to precompile VoronoiDelaunay [72f80fcb-8c52-57d9-aff0-40c1a3526986] to /home/nathanael/.julia/compiled/v1.0/VoronoiDelaunay/wbAGP.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
```

**Comment by skariel** [comment]
I'll look into it

**Comment by VPetukhov** [comment]
I've met some problems with deprecations because of old version of GeometricalPredicates package. Maybe it's your case. I created PR for fixing it: https://github.com/JuliaGeometry/VoronoiDelaunay.jl/pull/41.

**Comment by dkarrasch** [comment]
Fixed by #42.
